white_lower_h: 1
white_lower_s: 13
white_lower_v: 153
white_upper_h: 179
white_upper_s: 95
white_upper_v: 219

yellow_lower_h: 18
yellow_lower_s: 74
yellow_lower_v: 49
yellow_upper_h: 114
yellow_upper_s: 231
yellow_upper_v: 240
