white_lower_h: 0
white_lower_s: 0
white_lower_v: 180
white_upper_h: 179
white_upper_s: 60
white_upper_v: 255
yellow_lower_h: 20
yellow_lower_s: 80
yellow_lower_v: 100
yellow_upper_h: 35
yellow_upper_s: 255
yellow_upper_v: 255
