white_lower_h: 0
white_lower_s: 0
white_lower_v: 137
white_upper_h: 179
white_upper_s: 47
white_upper_v: 255

yellow_lower_h: 3
yellow_lower_s: 81
yellow_lower_v: 152
yellow_upper_h: 35
yellow_upper_s: 185
yellow_upper_v: 255
