baseline: 0.1
radius: 0.0318
k: 27.0
gain: 1.0
trim: 0
power_limit: 1
v_max: 0.5
encoder_resolution: 135
omega_max: 8.0
<<<<<<< Updated upstream
k_P: 5.0
k_I: 0.1
k_D: 0.2
max_omega: 6.0
v_0: 0.3
=======
k_P: 15.0
k_I: 1
k_D: 0.2
max_omega: 3.0
v_0: 1.0
>>>>>>> Stashed changes
k_heading: 0.5


#|    | Simulator | Duckiebot |
#| -- | --------- | --------- |
#| kp | 5         | 15        |
#| ki | 0.2       | 1         |
#| kd | 0.1       | 0.2       |